apiVersion: v1
data:
  masterPassword: cGFzU3ktZFM5RDktNklHU1QtcGpJSno=
  masterUser: YWRtaW4=
  password: Y0RJZGQtek1xQm0tZVZPZW0tdjdpTEU=
  user: ZGVtb3VzZXI=
  userPassword: T2JYeTgtWnVNSEEtRnIzalMtUlNGVFI=
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: flightctl-db-secret
  namespace: '{{ default "default" .Values.global.namespace }}'
type: Opaque
