apiVersion: v1
data:
  config.yaml: "database:\n    hostname: flightctl-db.open-cluster-management.svc.cluster.local\n    type: pgsql\n    port: 5432\n    name: flightctl\nservice: {}\nkv:\n    hostname: flightctl-kv.open-cluster-management.svc.cluster.local\n    port: 6379"
kind: ConfigMap
metadata:
  name: flightctl-worker-config
  namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
