name: Generate Onboarded Requested Component

on:
  workflow_dispatch: {}
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - onboard-request.yaml

jobs: 
  onboard-component:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Parse onboarding request details
        id: parse_yaml
        run: |
          # Parse YAML using yq and extract needed fields
          ls -la
          CONFIG_FILE="onboard-request.yaml"
          COMPONENT_NAME=$(yq e '.repo_name' $CONFIG_FILE)
          COMPONENT_DESCRIPTION=$(yq e '.repo_name' $CONFIG_FILE)
          COMPONENT_ENABLED=$(yq e '.repo_name' $CONFIG_FILE)
          echo "COMPONENT_NAME=$COMPONENT_NAME" >> $GITHUB_ENV
          echo "COMPONENT_DESCRIPTION=$COMPONENT_DESCRIPTION" >> $GITHUB_ENV
          echo "COMPONENT_ENABLED=$COMPONENT_ENABLED" >> $GITHUB_ENV

      - name: Add component entry to config file
        run: |
          echo "Attempting to add"

      - name: Insert component description into available-components doc
        run: |
          echo "Inserting $COMPONENT_NAME description into docs/available-components.md"

      - name: (Upstream) Validate image mapping
        run: |
          echo "Validating $COMPONENT_NAME upstream image mapping"

      - name: (Downstream) Validate image mapping
        run: |
          echo "Validating $COMPONENT_NAME downstream image mapping"

      - name: Build Component
        run: |
          echo "Building $COMPONENT_NAME component"